services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Site\SiteBackend\:
    resource: '../Classes/*'

  Site\SiteBackend\Configuration\Listener\AfterTcaCompilationListener:
    tags:
      - name: event.listener
        identifier: 'site-backend/tca-compilation-event'
        event: TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent

  Site\SiteBackend\Configuration\Listener\AfterCeDefaultTcaRetrievedListener:
    tags:
      - name: event.listener
        identifier: 'site-backend/tca-ce-default-tca-retrieved-event'
        event: Site\Core\Configuration\Event\AfterCeDefaultTcaRetrievedEvent
