services:
  Site\Backend\Listener\AfterTcaCompilationListener:
    tags:
      - name: event.listener
        identifier: 'site-backend/tca-compilation-listener'
        method: 'callback'
        event: TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent
