services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Site\SiteBackend\:
    resource: '../Classes/*'

  Site\SiteBackend\Listener\AfterTcaCompilationListener:
    tags:
      - name: event.listener
        identifier: 'site-backend/tca-compilation-listener'
        method: 'callback'
        event: TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent
