services:
  TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent:
    tags:
      - name: event.listener
        identifier: 'site-backend/tca-compilation-listener'
        method: 'callback'
        event: Site\Backend\Listener\AfterTcaCompilationListener
        after: 'after'
        before: 'before'
